TWEAK_NAME := PanCake

$(TWEAK_NAME)_FILES := $(TWEAK_NAME).xm
$(TWEAK_NAME)_CFLAGS := -fobjc-arc
$(TWEAK_NAME)_EXTRA_FRAMEWORKS := Cephei


include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
